name: Build and Create Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up .NET
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    # Build the project in Release mode
    - name: Build WinForms Project
      run: dotnet publish -c Release -r win-x64 --self-contained
      
    # List files in the output directory
    - name: List output files
      run: dir bin\Release\net6.0-windows\win-x64

    # Create the installer using WiX
    - name: Create MSI Installer with WiX
      run: |
        cd Installer
        candle CaixaSucata.wxs
        light CaixaSucata.wixobj -o CaixaSucataInstaller.msi  

    # Upload the installer artifact
    - name: Upload MSI Installer
      uses: actions/upload-artifact@v3
      with:
        name: Installer
        path: CaixaSucataInstaller.msi
